
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 17 17:36:42 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ARROWFUNCTION = 25;
  public static final int INCREMENT = 26;
  public static final int CONST = 5;
  public static final int NUMCONST = 48;
  public static final int CONTINUE = 20;
  public static final int LBRACEBRACKET = 3;
  public static final int MINUS = 32;
  public static final int DECREMENT = 27;
  public static final int LROUNDBRACKET = 11;
  public static final int LSQUAREBRACKET = 14;
  public static final int SEMICOLON = 6;
  public static final int AND = 29;
  public static final int LT = 41;
  public static final int OR = 28;
  public static final int COMMA = 7;
  public static final int CLASS = 9;
  public static final int DIV = 35;
  public static final int GEQ = 40;
  public static final int RBRACEBRACKET = 4;
  public static final int PLUS = 33;
  public static final int ASSIGN = 8;
  public static final int IF = 16;
  public static final int THIS = 44;
  public static final int DOT = 30;
  public static final int RROUNDBRACKET = 12;
  public static final int EOF = 0;
  public static final int RETURN = 21;
  public static final int NEW = 31;
  public static final int error = 1;
  public static final int MUL = 34;
  public static final int MOD = 36;
  public static final int NEQ = 38;
  public static final int IDENT = 47;
  public static final int BREAK = 19;
  public static final int VOID = 13;
  public static final int EQ = 37;
  public static final int FOREACH = 45;
  public static final int RSQUAREBRACKET = 15;
  public static final int COLON = 24;
  public static final int ELSE = 17;
  public static final int ENUM = 43;
  public static final int READ = 22;
  public static final int CHARCONST = 50;
  public static final int WHILE = 18;
  public static final int BOOLCONST = 49;
  public static final int EXTENDS = 10;
  public static final int PROG = 2;
  public static final int LEQ = 42;
  public static final int GT = 39;
  public static final int DO = 46;
  public static final int PRINT = 23;
}

